baseURL = "https://laptrinhcungbao.github.io/"
languageCode = "vi"
title = "Lập Trình Cùng Bảo"
theme = "hugo-PaperMod"

[params]
    defaultTheme = "dark"
    hidePageList = true      # Ẩn danh sách bài viết cũ
    showFullTextContent = true # Hiện nội dung HTML mình vừa viết

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Cho phép chạy HTML trong file .md

[menu]
  [[menu.main]]
    name = "Trang chủ"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Bài đăng"
    url = "/posts/cate"
    weight = 20

  [[menu.main]]
    name = "Tip học tập"
    url = "/tips" # Bạn có thể thay đổi đường dẫn này tùy theo cấu trúc file của bạn
    weight = 30

  [[menu.main]]
    name = "Thông tin của Bảo"
    url = "/about" # Đường dẫn đến trang giới thiệu bản thân
    weight = 40

  [[menu.main]]
    name = "Liên hệ"
    url = "/contact" # Đường dẫn đến trang liên hệ
    weight = 50