baseURL = "https://laptrinhcungbao.github.io/"
languageCode = "vi"
title = "Lập Trình Cùng Bảo"
theme = "hugo-PaperMod"

# Cấu hình menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 20

# Gộp tất cả params vào đây (Chỉ dùng một dòng [params] duy nhất)
[params]
    defaultTheme = "auto"
    googleAnalytics = ""
    displayFullContent = false
    showShareButtons = true
    showCodeCopyButtons = true

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
    section = ["HTML"]

[caches]
  [caches.images]
    dir = ":cacheDir/images"