baseURL = "https://laptrinhcungbao.github.io/"
languageCode = "vi"
title = "Lập Trình Cùng Bảo"
theme = "hugo-PaperMod"

[params]
    defaultTheme = "dark"
    hidePageList = true      # Ẩn danh sách bài viết cũ
    showFullTextContent = true # Hiện nội dung HTML mình vừa viết

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Cho phép chạy HTML trong file .md

[menu]
  [[menu.main]]
    name = "Trang chủ"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Bài đăng"
    url = "/posts/cate"
    weight = 20